version: '3.1'

services:
  db:
    image: mysql
    # container_name: db
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: sekolah
      MYSQL_USER: adminer
      MYSQL_PASSWORD: adminer
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - data:/var/lib/mysql

  # seeder:
  #   image: mysql
  #   volumes:
  #     - ./mysql/init/init.sql:/init.sql
  #   entrypoint:
  #     [
  #       'bash',
  #       '-c',
  #       'sleep 120 && mysql --user=root -ptoor --host=db --port=3306 sekolah < /init.sql && exit',
  #     ]
  #   depends_on:
  #     - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  data:
